version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: homestay-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: homestay-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=homestay
      - RABBITMQ_DEFAULT_PASS=homestay123
    ports:
      - "5672:5672"
      - "15672:15672"
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: homestay-prometheus
    volumes:
      - ./tools/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.1.0
    container_name: homestay-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./tools/monitoring/grafana-provisioning/:/etc/grafana/provisioning/
      - ./tools/monitoring/grafana-dashboard.json:/var/lib/grafana/dashboards/homestay-dashboard.json
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  es-data:
