version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: homestay-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: homestay-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=homestay
      - RABBITMQ_DEFAULT_PASS=homestay123
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  es-data:
