-- 全量表结构快照（从本地开发库导出，2026-08）
-- 用途：空库部署时在建表阶段生成完整结构，配合 Flyway baseline-on-migrate
--       （空库有表无 history → baseline 到 V49，跳过迁移执行；本地/增量环境不受影响）
-- 注意：1) 外键/CHECK 约束已剥离（完整性由 JPA 关系维护，业务层有归属校验）
--       2) 幂等：全部 IF NOT EXISTS，任何环境执行都安全
--       3) 视图不在此文件（由迁移/代码创建）
CREATE TABLE IF NOT EXISTS `ab_assignment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `experiment_id` bigint NOT NULL COMMENT '实验ID',
  `variant_id` bigint NOT NULL COMMENT '实验组ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_experiment_user` (`experiment_id`,`user_id`),
  UNIQUE KEY `UKjhu4mf3oedam7om3anajxw8xv` (`experiment_id`,`user_id`),
  KEY `idx_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AB实验用户分流记录表';
CREATE TABLE IF NOT EXISTS `ab_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `experiment_id` bigint NOT NULL COMMENT '实验ID',
  `variant_id` bigint NOT NULL COMMENT '实验组ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `event_type` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '事件类型: IMPRESSION/CLICK/CONVERT/ORDER',
  `event_value` decimal(12,2) DEFAULT NULL COMMENT '事件数值（如订单金额）',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_experiment_variant_event` (`experiment_id`,`variant_id`,`event_type`,`created_at`),
  KEY `idx_user_event` (`user_id`,`event_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AB实验事件表';
CREATE TABLE IF NOT EXISTS `ab_experiment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '实验名称',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '实验描述',
  `experiment_type` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '实验类型: CAMPAIGN/COUPON_TEMPLATE',
  `target_id` bigint NOT NULL COMMENT '目标对象ID（活动ID或券模板ID）',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT/RUNNING/PAUSED/ENDED',
  `start_at` datetime DEFAULT NULL COMMENT '开始时间',
  `end_at` datetime DEFAULT NULL COMMENT '结束时间',
  `traffic_percent` int NOT NULL DEFAULT '100' COMMENT '参与实验流量百分比(0-100)',
  `primary_metric` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CONVERSION' COMMENT '主要指标: CONVERSION/ORDER_RATE/GMV',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_target_type` (`target_id`,`experiment_type`),
  KEY `idx_status` (`status`,`start_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AB实验表';
CREATE TABLE IF NOT EXISTS `ab_variant` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `experiment_id` bigint NOT NULL COMMENT '实验ID',
  `variant_key` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组标识: control/variant_a/variant_b',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组名称',
  `traffic_ratio` int NOT NULL DEFAULT '50' COMMENT '流量占比(0-100)，所有组之和应为100',
  `config_json` text COLLATE utf8mb4_unicode_ci COMMENT '实验配置JSON（如不同折扣力度、不同文案）',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_experiment_variant` (`experiment_id`,`variant_key`),
  KEY `idx_experiment` (`experiment_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AB实验组表';
CREATE TABLE IF NOT EXISTS `admin` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_gfn44sntic2k93auag97juyij` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=912 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `amenities` (
  `value` varchar(50) NOT NULL,
  `label` varchar(100) NOT NULL,
  `active` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `icon` varchar(100) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `usage_count` bigint DEFAULT NULL,
  `category_code` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`value`),
  KEY `FKb48d658cj1lf0j9jvatps3y6r` (`category_code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `amenity_categories` (
  `code` varchar(50) NOT NULL,
  `icon` varchar(100) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `sort_order` int DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `announcement` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `category` varchar(50) NOT NULL,
  `content` text NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `end_time` datetime(6) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `published_at` datetime(6) DEFAULT NULL,
  `publisher_id` bigint DEFAULT NULL,
  `publisher_name` varchar(100) DEFAULT NULL,
  `start_time` datetime(6) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `title` varchar(200) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_category` (`category`),
  KEY `idx_published_at` (`published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `banners` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Banner标题',
  `subtitle` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '副标题/描述',
  `image_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '背景图片URL（优先使用）',
  `link_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '点击跳转链接',
  `bg_gradient` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'CSS渐变背景（无图片时使用）',
  `sort_order` int DEFAULT '0' COMMENT '排序权重，越小越靠前',
  `enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='首页运营Banner表';
CREATE TABLE IF NOT EXISTS `check_in_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL,
  `check_in_method` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `checked_in_at` datetime DEFAULT NULL,
  `check_in_operator_id` bigint DEFAULT NULL,
  `check_in_operator_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `check_in_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `door_password` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lockbox_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_description` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_until` datetime DEFAULT NULL,
  `remark` text COLLATE utf8mb4_unicode_ci,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_check_in_order_id` (`order_id`),
  KEY `idx_check_in_code` (`check_in_code`)
) ENGINE=InnoDB AUTO_INCREMENT=15641 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `check_out_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL,
  `check_out_method` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `checked_out_at` datetime DEFAULT NULL,
  `check_out_operator_id` bigint DEFAULT NULL,
  `check_out_operator_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `actual_nights` int DEFAULT NULL,
  `deposit_amount` decimal(10,2) DEFAULT NULL,
  `deposit_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extra_charges` decimal(10,2) DEFAULT NULL,
  `extra_charges_description` text COLLATE utf8mb4_unicode_ci,
  `settlement_amount` decimal(10,2) DEFAULT NULL,
  `remark` text COLLATE utf8mb4_unicode_ci,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'PENDING',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_check_out_order_id` (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13746 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `conversations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `last_message_at` datetime(6) DEFAULT NULL,
  `last_message_content` text,
  `unread_guest_count` int DEFAULT NULL,
  `unread_host_count` int DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `guest_id` bigint NOT NULL,
  `homestay_id` bigint DEFAULT NULL,
  `host_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversation_unique` (`homestay_id`,`host_id`,`guest_id`),
  KEY `idx_conversation_host` (`host_id`),
  KEY `idx_conversation_guest` (`guest_id`),
  KEY `idx_conversation_homestay` (`homestay_id`),
  KEY `idx_conversation_updated` (`updated_at` DESC)) ENGINE=InnoDB AUTO_INCREMENT=5981 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `coupon_analytics` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint DEFAULT NULL COMMENT '优惠券模板ID（活动相关则为NULL）',
  `campaign_id` bigint DEFAULT NULL COMMENT '活动ID（券相关则为NULL）',
  `channel` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '渠道: HOME_BANNER/HOMESTAY_DETAIL/ORDER_SUCCESS/SHARE_LINK/SMS',
  `event_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '事件类型: IMPRESSION/CLICK/CLAIM/LOCK/USE/EXPIRE',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `homestay_id` bigint DEFAULT NULL COMMENT '房源ID（如涉及）',
  `order_id` bigint DEFAULT NULL COMMENT '订单ID（如涉及）',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_template_event` (`template_id`,`event_type`,`created_at`),
  KEY `idx_campaign_event` (`campaign_id`,`event_type`,`created_at`),
  KEY `idx_channel_created` (`channel`,`created_at`),
  KEY `idx_user_event` (`user_id`,`event_type`,`created_at`),
  KEY `idx_event_created` (`event_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠券分析事件表';
CREATE TABLE IF NOT EXISTS `coupon_batch_issue_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING/SUCCESS/FAILED',
  `error_msg` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_task_user` (`task_id`,`user_id`),
  KEY `idx_task_status` (`task_id`,`status`)) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='批量发券任务明细表';
CREATE TABLE IF NOT EXISTS `coupon_batch_issue_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NOT NULL COMMENT '优惠券模板ID',
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务名称',
  `filter_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '筛选类型: ALL/AT_RISK/HIGH_VALUE/NEW_USER/NO_ORDER_30D',
  `filter_params_json` text COLLATE utf8mb4_unicode_ci COMMENT '筛选参数JSON',
  `total_count` int NOT NULL DEFAULT '0' COMMENT '目标用户总数',
  `success_count` int NOT NULL DEFAULT '0' COMMENT '成功发放数',
  `fail_count` int NOT NULL DEFAULT '0' COMMENT '失败数',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING/PROCESSING/COMPLETED/FAILED',
  `error_msg` text COLLATE utf8mb4_unicode_ci COMMENT '错误信息',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_status_created` (`status`,`created_at`),
  KEY `idx_template` (`template_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='批量发券任务表';
CREATE TABLE IF NOT EXISTS `coupon_template` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '券名称',
  `coupon_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '券类型: CASH(现金券), DISCOUNT(折扣券), FULL_REDUCTION(满减券)',
  `face_value` decimal(12,2) DEFAULT NULL COMMENT '面值（现金券用）',
  `discount_rate` decimal(3,2) DEFAULT NULL COMMENT '折扣率（折扣券用）',
  `threshold_amount` decimal(12,2) DEFAULT NULL COMMENT '使用门槛金额',
  `max_discount` decimal(12,2) DEFAULT NULL COMMENT '最大优惠金额',
  `total_stock` int NOT NULL DEFAULT '0' COMMENT '总库存',
  `issued_count` int NOT NULL DEFAULT '0' COMMENT '已领取数量',
  `per_user_limit` int NOT NULL DEFAULT '1' COMMENT '每用户限领数量',
  `valid_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '有效期类型: FIXED_TIME(固定时间), AFTER_CLAIM_DAYS(领取后N天)',
  `valid_days` int DEFAULT NULL COMMENT '领取后有效天数',
  `valid_start_at` datetime DEFAULT NULL COMMENT '固定有效期开始',
  `valid_end_at` datetime DEFAULT NULL COMMENT '固定有效期结束',
  `scope_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ALL' COMMENT '适用范围类型',
  `scope_value_json` text COLLATE utf8mb4_unicode_ci COMMENT '适用范围值JSON',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT/ACTIVE/PAUSED/EXPIRED',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `subsidy_bearer` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PLATFORM' COMMENT '承担方: PLATFORM(平台), HOST(房东), MIXED(混合)',
  `host_id` bigint DEFAULT NULL COMMENT '房东用户ID，平台券为NULL',
  `is_new_user_coupon` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为新人专属券：1=是，0=否',
  `auto_issue_trigger` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'NONE' COMMENT '自动发放触发条件: NONE/ORDER_COMPLETED/FIRST_ORDER/REGISTER',
  `stack_group` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'DEFAULT' COMMENT '互斥组ID，同组券不可叠加',
  PRIMARY KEY (`id`),
  KEY `idx_status_time` (`status`,`valid_start_at`,`valid_end_at`),
  KEY `idx_host_coupon_template` (`host_id`,`status`),
  KEY `idx_stack_group` (`stack_group`,`status`),
  KEY `idx_auto_issue_trigger` (`auto_issue_trigger`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠券模板表';
CREATE TABLE IF NOT EXISTS `dispute_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL,
  `dispute_reason` text COLLATE utf8mb4_unicode_ci COMMENT '争议原因',
  `raised_by` bigint DEFAULT NULL COMMENT '发起争议的用户ID',
  `raised_at` datetime DEFAULT NULL COMMENT '发起时间',
  `resolution` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仲裁结果：APPROVED/REJECTED',
  `resolved_by` bigint DEFAULT NULL COMMENT '仲裁人ID',
  `resolved_at` datetime DEFAULT NULL COMMENT '仲裁时间',
  `resolution_note` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仲裁备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_raised_by` (`raised_by`),
  KEY `idx_resolved_by` (`resolved_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `earnings` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` decimal(10,2) NOT NULL,
  `checkin_date` date NOT NULL,
  `checkout_date` date NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `nights` int NOT NULL,
  `status` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `homestay_id` bigint NOT NULL,
  `host_id` bigint NOT NULL,
  `order_id` bigint NOT NULL,
  `is_test` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKj5r6pxyd8vqglykedwg78ivk2` (`homestay_id`),
  KEY `FKmk2cff6mwxijc8ttu1ykbhhk8` (`host_id`),
  KEY `FKfv0fw87jpvlaka59ef3hiebef` (`order_id`)) ENGINE=InnoDB AUTO_INCREMENT=6960 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `holiday_calendar` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `region_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CN',
  `is_holiday` tinyint(1) NOT NULL DEFAULT '1',
  `is_makeup_workday` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_date_region` (`date`,`region_code`),
  KEY `idx_date` (`date`),
  KEY `idx_region_date` (`region_code`,`date`)
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='节假日日历表';
CREATE TABLE IF NOT EXISTS `homestay_amenity` (
  `homestay_id` bigint NOT NULL,
  `amenity_id` varchar(50) NOT NULL,
  PRIMARY KEY (`homestay_id`,`amenity_id`),
  KEY `FK51mhfxcl1u9mic6phbse9eb9` (`amenity_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `homestay_audit_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `homestay_id` bigint NOT NULL,
  `reviewer_id` bigint NOT NULL,
  `old_status` varchar(20) DEFAULT NULL,
  `new_status` varchar(20) NOT NULL,
  `action_type` varchar(20) NOT NULL,
  `review_reason` text,
  `review_notes` text,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_homestay_audit_homestay_id` (`homestay_id`),
  KEY `idx_homestay_audit_reviewer_id` (`reviewer_id`),
  KEY `idx_homestay_audit_created_at` (`created_at`),
  KEY `idx_homestay_audit_status` (`new_status`),
  KEY `idx_homestay_audit_action_type` (`action_type`)) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `homestay_availability` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `homestay_id` bigint NOT NULL,
  `date` date NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'AVAILABLE',
  `order_id` bigint DEFAULT NULL,
  `locked` tinyint(1) NOT NULL DEFAULT '0',
  `lock_expires_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `source` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '占用来源: ORDER/MANUAL/SYSTEM/MAINTENANCE',
  `reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '不可用原因',
  `note` text COLLATE utf8mb4_unicode_ci COMMENT '房东日历备注',
  `created_by` bigint DEFAULT NULL COMMENT '操作人用户ID',
  `custom_price` decimal(10,2) DEFAULT NULL COMMENT '房东自定义每日价格',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_homestay_date` (`homestay_id`,`date`),
  KEY `idx_homestay_date` (`homestay_id`,`date`),
  KEY `idx_date_status` (`date`,`status`),
  KEY `idx_availability_source` (`source`)
) ENGINE=InnoDB AUTO_INCREMENT=48901 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房源可用性日历表，用于记录每个房源每天的预订状态';
CREATE TABLE IF NOT EXISTS `homestay_groups` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '分组名称',
  `code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分组编码',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '分组描述',
  `icon` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图标',
  `color` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '颜色标识',
  `owner_id` bigint NOT NULL COMMENT '房东ID',
  `sort_order` int DEFAULT '0' COMMENT '排序顺序',
  `is_default` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为默认分组',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_group_owner` (`owner_id`),
  KEY `idx_group_code` (`code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房源分组表';
CREATE TABLE IF NOT EXISTS `homestay_images` (
  `homestay_id` bigint NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  KEY `FKrh41oto9d1d8q5k2bmnj3xv8x` (`homestay_id`)) ENGINE=InnoDB AUTO_INCREMENT=25010 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `homestay_types` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) NOT NULL,
  `code` varchar(255) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `description` text,
  `icon` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `sort_order` int NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `category_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_1l6du2ayrvxvevif6j79l9i9c` (`code`),
  KEY `FKxuuhe1dywasqopy8wr9r4wkm` (`category_id`)) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `homestays` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `cover_image` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `description` text,
  `featured` bit(1) DEFAULT NULL,
  `max_guests` int NOT NULL,
  `min_nights` int NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `status` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `owner_id` bigint NOT NULL,
  `address_detail` varchar(255) NOT NULL,
  `city_code` varchar(10) NOT NULL,
  `city_text` varchar(255) DEFAULT NULL,
  `district_code` varchar(10) DEFAULT NULL,
  `district_text` varchar(255) DEFAULT NULL,
  `province_code` varchar(10) NOT NULL,
  `province_text` varchar(255) DEFAULT NULL,
  `auto_confirm` tinyint(1) DEFAULT '0' COMMENT '自动确认订单：true=直接付费，false=房东确认制',
  `cancel_policy_type` int DEFAULT NULL,
  `check_in_time` varchar(50) DEFAULT NULL,
  `check_out_time` varchar(50) DEFAULT NULL,
  `house_rules` text,
  `max_nights` int DEFAULT NULL COMMENT '最大入住晚数，null=不限制',
  `group_id` bigint DEFAULT NULL COMMENT '所属分组ID',
  `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
  `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
  PRIMARY KEY (`id`),
  KEY `FKmdanrkfqnooijobcl7stsyb5t` (`owner_id`),
  KEY `idx_homestays_auto_confirm` (`auto_confirm`),
  KEY `idx_homestay_group` (`group_id`),
  KEY `idx_homestays_coordinates` (`latitude`,`longitude`),
  KEY `idx_homestays_status_created_at` (`status`,`created_at` DESC)) ENGINE=InnoDB AUTO_INCREMENT=5423 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `login_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(50) DEFAULT NULL,
  `login_status` varchar(20) NOT NULL,
  `login_time` datetime(6) NOT NULL,
  `login_type` varchar(20) NOT NULL,
  `logout_time` datetime(6) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `username` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_username` (`username`),
  KEY `idx_login_time` (`login_time`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `messages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `content` text NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `is_read` bit(1) DEFAULT NULL,
  `read_at` datetime(6) DEFAULT NULL,
  `conversation_id` bigint NOT NULL,
  `sender_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_message_conversation` (`conversation_id`),
  KEY `idx_message_conversation_created` (`conversation_id`,`created_at` DESC),
  KEY `idx_message_sender` (`sender_id`)) ENGINE=InnoDB AUTO_INCREMENT=17142 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `notification_broadcast_jobs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Broadcast job status',
  `initiated_by` bigint DEFAULT NULL COMMENT 'Admin user id when available',
  `initiated_by_username` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Admin username when available',
  `content_summary` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Trimmed content summary',
  `content_length` int NOT NULL COMMENT 'Trimmed content length',
  `target_count` int NOT NULL DEFAULT '0' COMMENT 'Enabled recipient count',
  `success_count` int NOT NULL DEFAULT '0' COMMENT 'Created notification count',
  `failure_count` int NOT NULL DEFAULT '0' COMMENT 'Failed notification count',
  `failure_reason` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Failure or rate limit reason',
  `submitted_at` datetime NOT NULL COMMENT 'Submitted time',
  `started_at` datetime DEFAULT NULL COMMENT 'Processing start time',
  `completed_at` datetime DEFAULT NULL COMMENT 'Processing completion time',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  PRIMARY KEY (`id`),
  KEY `idx_notification_broadcast_status_submitted` (`status`,`submitted_at`),
  KEY `idx_notification_broadcast_initiator_submitted` (`initiated_by`,`submitted_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Notification broadcast jobs';
CREATE TABLE IF NOT EXISTS `notification_preferences` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `domain` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '通知业务域',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启该域通知',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_domain` (`user_id`,`domain`),
  KEY `idx_notification_prefs_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户通知偏好';
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '通知唯一ID',
  `user_id` bigint NOT NULL COMMENT '接收通知的用户ID (关联 users 表)',
  `actor_id` bigint DEFAULT NULL COMMENT '触发通知的用户ID (可选, 关联 users 表)',
  `type` varchar(50) NOT NULL COMMENT '通知类型 (例如: BOOKING_REQUEST, NEW_MESSAGE)',
  `entity_type` varchar(50) DEFAULT NULL COMMENT '关联实体类型 (可选, 例如: BOOKING, HOMESTAY)',
  `entity_id` varchar(255) DEFAULT NULL COMMENT '关联实体ID (可选, 例如: 订单号, 民宿ID)',
  `content` text NOT NULL COMMENT '通知内容文本',
  `is_read` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已读',
  `read_at` timestamp NULL DEFAULT NULL COMMENT '标记已读的时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_notification_user_created` (`user_id`,`created_at` DESC),
  KEY `idx_notification_user_id` (`user_id`),
  KEY `idx_notification_type` (`type`),
  KEY `idx_notification_user_read` (`user_id`,`is_read`),
  KEY `idx_notification_read_at` (`is_read`,`read_at`)
) ENGINE=InnoDB AUTO_INCREMENT=64842 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户通知表';
CREATE TABLE IF NOT EXISTS `operation_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `detail` text,
  `ip_address` varchar(50) DEFAULT NULL,
  `operate_time` datetime(6) DEFAULT NULL,
  `operation_type` varchar(50) DEFAULT NULL,
  `operator` varchar(100) DEFAULT NULL,
  `resource` varchar(50) DEFAULT NULL,
  `resource_id` varchar(100) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_operate_time` (`operate_time`),
  KEY `idx_operator` (`operator`),
  KEY `idx_resource` (`resource`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `order_price_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `quote_token` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '报价令牌',
  `room_original_amount` decimal(12,2) NOT NULL COMMENT '原始房费合计',
  `daily_price_json` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '每日价格明细JSON',
  `activity_discount_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '活动优惠',
  `full_reduction_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '满减优惠',
  `coupon_discount_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '优惠券优惠',
  `platform_discount_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '平台承担优惠',
  `host_discount_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '房东承担优惠',
  `cleaning_fee` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '清洁费',
  `service_fee` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '服务费',
  `payable_amount` decimal(12,2) NOT NULL COMMENT '用户实付金额',
  `host_receivable_amount` decimal(12,2) NOT NULL COMMENT '房东应收金额',
  `pricing_detail_json` text COLLATE utf8mb4_unicode_ci COMMENT '完整定价明细JSON',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_id` (`order_id`),
  KEY `idx_order` (`order_id`),
  KEY `idx_payable_amount` (`order_id`,`payable_amount`)) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单价格快照表';
CREATE TABLE IF NOT EXISTS `orders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `check_in_date` date NOT NULL,
  `check_out_date` date NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `guest_count` int NOT NULL,
  `guest_phone` varchar(20) DEFAULT NULL,
  `nights` int NOT NULL,
  `order_number` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `remark` text,
  `status` varchar(255) NOT NULL,
  `total_amount` decimal(10,2) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `guest_id` bigint NOT NULL,
  `homestay_id` bigint NOT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `payment_status` varchar(255) DEFAULT NULL,
  `refund_type` varchar(50) DEFAULT NULL,
  `refund_reason` text,
  `refund_amount` decimal(10,2) DEFAULT NULL,
  `refund_initiated_by` bigint DEFAULT NULL,
  `refund_initiated_at` timestamp NULL DEFAULT NULL,
  `refund_processed_by` bigint DEFAULT NULL,
  `refund_processed_at` timestamp NULL DEFAULT NULL,
  `refund_transaction_id` varchar(100) DEFAULT NULL,
  `idempotency_key` varchar(64) DEFAULT NULL,
  `refund_rejection_reason` varchar(500) DEFAULT NULL,
  `checked_in_at` datetime DEFAULT NULL,
  `checked_out_at` datetime DEFAULT NULL,
  `check_in_code` varchar(32) DEFAULT NULL,
  `door_password` varchar(32) DEFAULT NULL,
  `auto_checkin_time` varchar(5) DEFAULT NULL,
  `deposit_amount` decimal(10,2) DEFAULT NULL,
  `dispute_raised_at` datetime(6) DEFAULT NULL,
  `dispute_raised_by` bigint DEFAULT NULL,
  `dispute_reason` text,
  `dispute_resolution` varchar(20) DEFAULT NULL,
  `dispute_resolution_note` varchar(500) DEFAULT NULL,
  `dispute_resolved_at` datetime(6) DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `completed_at` datetime DEFAULT NULL COMMENT '订单完成时间（状态变为 COMPLETED 时设置）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_nthkiu7pgmnqnu86i2jyoe2v7` (`order_number`),
  UNIQUE KEY `idx_orders_booking_unique` (`homestay_id`,`check_in_date`,`check_out_date`),
  UNIQUE KEY `idx_orders_idempotency_key` (`idempotency_key`),
  KEY `idx_orders_refund_type` (`refund_type`),
  KEY `idx_orders_refund_initiated_by` (`refund_initiated_by`),
  KEY `idx_orders_refund_processed_by` (`refund_processed_by`),
  KEY `idx_orders_homestay_dates_status` (`homestay_id`,`check_in_date`,`check_out_date`,`status`),
  KEY `idx_orders_status` (`status`),
  KEY `idx_orders_homestay_status_dates` (`homestay_id`,`status`,`check_in_date`,`check_out_date`),
  KEY `idx_orders_homestay_date_range` (`homestay_id`,`check_in_date`,`check_out_date`),
  KEY `idx_homestay_dates` (`homestay_id`,`check_in_date`,`check_out_date`),
  KEY `idx_payment_status` (`payment_status`),
  KEY `idx_orders_homestay_checkin` (`homestay_id`,`check_in_date`),
  KEY `idx_orders_status_check` (`status`,`check_in_date`,`check_out_date`),
  KEY `idx_orders_guest_idempotency` (`guest_id`,`idempotency_key`),
  KEY `idx_orders_homestay_created_at` (`homestay_id`,`created_at`)) ENGINE=InnoDB AUTO_INCREMENT=8316 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `payment_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `payment_method` varchar(20) NOT NULL COMMENT '支付方式 (ALIPAY, WECHAT)',
  `out_trade_no` varchar(64) NOT NULL COMMENT '商户订单号',
  `transaction_id` varchar(64) DEFAULT NULL COMMENT '支付宝交易号',
  `amount` decimal(10,2) NOT NULL COMMENT '支付金额',
  `status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '支付状态 (PENDING, SUCCESS, FAILED)',
  `request_params` text COMMENT '请求参数JSON',
  `response_params` text COMMENT '响应参数JSON',
  `notify_params` text COMMENT '回调参数JSON',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` bigint DEFAULT NULL,
  `need_real_refund` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `out_trade_no` (`out_trade_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_out_trade_no` (`out_trade_no`),
  KEY `idx_transaction_id` (`transaction_id`),
  KEY `idx_payment_method` (`payment_method`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)) ENGINE=InnoDB AUTO_INCREMENT=11859 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付记录表';
CREATE TABLE IF NOT EXISTS `pricing_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则名称',
  `scope_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作用域: GLOBAL/CITY/HOST/GROUP/HOMESTAY/TYPE',
  `scope_value_json` text COLLATE utf8mb4_unicode_ci COMMENT '作用域值JSON',
  `rule_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则类型: WEEKEND/HOLIDAY/DATE_RANGE/EARLY_BIRD/LONG_STAY',
  `adjustment_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '调价方式: MULTIPLY/DISCOUNT_RATE/AMOUNT_OFF/FIXED_PRICE',
  `adjustment_value` decimal(12,4) NOT NULL COMMENT '调价数值',
  `priority` int NOT NULL DEFAULT '0' COMMENT '优先级，数值越小越优先',
  `stackable` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否可叠加',
  `start_date` date DEFAULT NULL COMMENT '规则生效开始日期',
  `end_date` date DEFAULT NULL COMMENT '规则生效结束日期',
  `min_nights` int DEFAULT NULL COMMENT '最少入住夜数',
  `max_nights` int DEFAULT NULL COMMENT '最多入住夜数',
  `min_advance_days` int DEFAULT NULL COMMENT '最少提前预订天数',
  `max_advance_days` int DEFAULT NULL COMMENT '最多提前预订天数',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_scope` (`scope_type`,`enabled`),
  KEY `idx_rule_type` (`rule_type`,`enabled`),
  KEY `idx_date_range` (`start_date`,`end_date`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='价格规则表';
CREATE TABLE IF NOT EXISTS `promotion_campaign` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动名称',
  `campaign_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动类型: FLASH_SALE(限时折扣), FULL_REDUCTION(满减), HOMESTAY_DISCOUNT(房源折扣)',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT/ACTIVE/PAUSED/ENDED',
  `start_at` datetime DEFAULT NULL COMMENT '开始时间',
  `end_at` datetime DEFAULT NULL COMMENT '结束时间',
  `priority` int NOT NULL DEFAULT '0' COMMENT '优先级，数值越大越优先',
  `stackable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可与其他活动叠加',
  `budget_total` decimal(12,2) DEFAULT NULL COMMENT '总预算，null表示无限制',
  `budget_used` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '已使用预算',
  `subsidy_bearer` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PLATFORM' COMMENT '承担方: PLATFORM(平台), HOST(房东), MIXED(混合)',
  `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `host_id` bigint DEFAULT NULL COMMENT '房东用户ID，平台活动为NULL',
  `budget_alert_threshold` decimal(5,2) DEFAULT '0.80' COMMENT '预算预警阈值，如0.8表示80%',
  `budget_alert_triggered` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已触发预算预警',
  PRIMARY KEY (`id`),
  KEY `idx_status_time` (`status`,`start_at`,`end_at`),
  KEY `idx_priority` (`priority`),
  KEY `idx_host_campaign` (`host_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='营销活动表';
CREATE TABLE IF NOT EXISTS `promotion_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `campaign_id` bigint NOT NULL COMMENT '活动ID',
  `rule_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则类型: AMOUNT_OFF(固定金额减免), PERCENT_OFF(百分比折扣), FULL_REDUCTION(满减), PER_NIGHT_OFF(每晚减免)',
  `threshold_amount` decimal(12,2) DEFAULT NULL COMMENT '门槛金额（满减/满折用）',
  `discount_amount` decimal(12,2) DEFAULT NULL COMMENT '固定优惠金额',
  `discount_rate` decimal(3,2) DEFAULT NULL COMMENT '折扣率，如0.9表示9折',
  `max_discount` decimal(12,2) DEFAULT NULL COMMENT '最大优惠金额',
  `min_nights` int DEFAULT NULL COMMENT '最小入住晚数',
  `max_nights` int DEFAULT NULL COMMENT '最大入住晚数',
  `scope_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ALL' COMMENT '范围类型: ALL, CITY, HOMESTAY, GROUP, HOST, TYPE',
  `scope_value_json` text COLLATE utf8mb4_unicode_ci COMMENT '范围值JSON',
  `first_order_only` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否仅限首单',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tier_config_json` text COLLATE utf8mb4_unicode_ci COMMENT '阶梯配置JSON，如 [{"threshold":300,"discount":30},{"threshold":500,"discount":60}]',
  PRIMARY KEY (`id`),
  KEY `idx_campaign` (`campaign_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='活动规则表';
CREATE TABLE IF NOT EXISTS `promotion_usage` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `campaign_id` bigint DEFAULT NULL COMMENT '活动ID',
  `coupon_id` bigint DEFAULT NULL COMMENT '用户券ID',
  `discount_amount` decimal(12,2) NOT NULL COMMENT '优惠金额',
  `bearer` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '承担方: PLATFORM / HOST',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'LOCKED' COMMENT '状态: LOCKED/USED/RELEASED/REFUNDED',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_order` (`order_id`),
  KEY `idx_user_campaign` (`user_id`,`campaign_id`),
  KEY `idx_bearer_status` (`bearer`,`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_campaign_bearer` (`campaign_id`,`bearer`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠使用流水表';
CREATE TABLE IF NOT EXISTS `referral_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `referral_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '邀请码',
  `inviter_id` bigint NOT NULL COMMENT '邀请人用户ID',
  `template_id_for_invitee` bigint DEFAULT NULL COMMENT '被邀请人奖励券模板ID',
  `template_id_for_inviter` bigint DEFAULT NULL COMMENT '邀请人奖励券模板ID',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/USED/EXPIRED',
  `used_count` int NOT NULL DEFAULT '0' COMMENT '已被使用次数',
  `max_uses` int NOT NULL DEFAULT '1' COMMENT '最大可使用次数',
  `expire_at` datetime DEFAULT NULL COMMENT '邀请码过期时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `referral_code` (`referral_code`),
  KEY `idx_code` (`referral_code`),
  KEY `idx_inviter` (`inviter_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='邀请裂变记录表';
CREATE TABLE IF NOT EXISTS `refund_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL,
  `payment_method` varchar(20) NOT NULL,
  `out_trade_no` varchar(64) DEFAULT NULL,
  `trade_no` varchar(64) DEFAULT NULL,
  `refund_amount` decimal(10,2) NOT NULL,
  `refund_reason` text,
  `refund_status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `refund_type` varchar(50) DEFAULT NULL,
  `out_request_no` varchar(64) DEFAULT NULL,
  `refund_trade_no` varchar(64) DEFAULT NULL,
  `request_params` text,
  `response_params` text,
  `error_message` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_refund_records_order_id` (`order_id`),
  KEY `idx_refund_records_status` (`refund_status`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `review_images` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `review_id` bigint NOT NULL,
  `image_url` varchar(500) NOT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_review_images_review_id` (`review_id`),
  KEY `idx_review_images_sort_order` (`sort_order`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `reviews` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `content` text NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `host_reply` text,
  `rating` int NOT NULL,
  `reply_time` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `homestay_id` bigint NOT NULL,
  `order_id` bigint DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `accuracy_rating` int DEFAULT NULL,
  `check_in_rating` int DEFAULT NULL,
  `cleanliness_rating` int DEFAULT NULL,
  `communication_rating` int DEFAULT NULL,
  `create_time` datetime(6) DEFAULT NULL,
  `is_public` bit(1) DEFAULT NULL,
  `location_rating` int DEFAULT NULL,
  `response` text,
  `response_time` datetime(6) DEFAULT NULL,
  `update_time` datetime(6) DEFAULT NULL,
  `value_rating` int DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FKqwgq1lxgahsxdspnwqfac6sv6` (`order_id`),
  KEY `FKcgy7qjc1r99dp117y9en6lxye` (`user_id`),
  KEY `idx_reviews_deleted` (`deleted`),
  KEY `idx_reviews_homestay_public_deleted` (`homestay_id`,`is_public`,`deleted`)) ENGINE=InnoDB AUTO_INCREMENT=3047 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `system_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `category` varchar(50) DEFAULT NULL,
  `config_key` varchar(100) NOT NULL,
  `config_name` varchar(100) NOT NULL,
  `config_value` varchar(2000) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_npsxm1erd0lbetjn5d3ayrsof` (`config_key`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `type_categories` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `description` text,
  `name` varchar(255) NOT NULL,
  `sort_order` int NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `user_behavior_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint DEFAULT NULL COMMENT '用户ID（未登录为NULL）',
  `session_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会话ID',
  `event_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '事件类型: VIEW/SEARCH/CLICK/FAVORITE/BOOKING/SHARE',
  `homestay_id` bigint DEFAULT NULL COMMENT '房源ID（如涉及）',
  `keyword` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '搜索关键词',
  `city_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '城市代码',
  `type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '房源类型',
  `price` decimal(12,2) DEFAULT NULL COMMENT '房源价格快照',
  `extra_json` json DEFAULT NULL COMMENT '扩展字段',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_event` (`user_id`,`event_type`,`created_at`),
  KEY `idx_session_event` (`session_id`,`created_at`),
  KEY `idx_homestay_event` (`homestay_id`,`event_type`,`created_at`),
  KEY `idx_event_type_created` (`event_type`,`created_at`),
  KEY `idx_city_event` (`city_code`,`event_type`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户行为事件表';
CREATE TABLE IF NOT EXISTS `user_coupon` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NOT NULL COMMENT '券模板ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `coupon_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '券码',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'AVAILABLE' COMMENT '状态: AVAILABLE/LOCKED/USED/EXPIRED',
  `locked_order_id` bigint DEFAULT NULL COMMENT '锁定订单ID',
  `locked_at` datetime DEFAULT NULL COMMENT '锁定时间',
  `used_order_id` bigint DEFAULT NULL COMMENT '使用订单ID',
  `used_at` datetime DEFAULT NULL COMMENT '使用时间',
  `expire_at` datetime NOT NULL COMMENT '过期时间',
  `snapshot_face_value` decimal(12,2) DEFAULT NULL,
  `snapshot_discount_rate` decimal(3,2) DEFAULT NULL,
  `snapshot_threshold_amount` decimal(12,2) DEFAULT NULL,
  `snapshot_max_discount` decimal(12,2) DEFAULT NULL,
  `snapshot_scope_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `snapshot_scope_value_json` text COLLATE utf8mb4_unicode_ci,
  `snapshot_subsidy_bearer` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `coupon_code` (`coupon_code`),
  KEY `template_id` (`template_id`),
  KEY `idx_user_status` (`user_id`,`status`,`expire_at`),
  KEY `idx_locked_order` (`locked_order_id`),
  KEY `idx_used_order` (`used_order_id`)) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户优惠券表';
CREATE TABLE IF NOT EXISTS `user_favorites` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `homestay_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK1y2tk66350efwgr790r2xcykj` (`user_id`,`homestay_id`),
  KEY `FK2a2e6sq7ve5sh4exxuqmllnn6` (`homestay_id`)) ENGINE=InnoDB AUTO_INCREMENT=16046 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `user_preference_profile` (
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `preferred_city_json` json DEFAULT NULL COMMENT '偏好城市及权重',
  `preferred_type_json` json DEFAULT NULL COMMENT '偏好房型及权重',
  `preferred_amenity_json` json DEFAULT NULL COMMENT '偏好设施及权重',
  `min_price` decimal(12,2) DEFAULT NULL COMMENT '历史浏览价格下限',
  `max_price` decimal(12,2) DEFAULT NULL COMMENT '历史浏览价格上限',
  `last_active_at` datetime DEFAULT NULL COMMENT '最后活跃时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  KEY `idx_last_active` (`last_active_at`),
  KEY `idx_price_range` (`min_price`,`max_price`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户偏好画像表';
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_time` datetime(6) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `enabled` bit(1) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `update_time` datetime(6) DEFAULT NULL,
  `username` varchar(255) NOT NULL,
  `id_card` varchar(255) DEFAULT NULL,
  `real_name` varchar(255) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `verification_status` varchar(255) DEFAULT NULL,
  `reset_token` varchar(255) DEFAULT NULL,
  `reset_token_expiry` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `last_login` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `companions` text,
  `host_accommodations` int DEFAULT NULL,
  `host_rating` double DEFAULT NULL,
  `host_response_rate` varchar(255) DEFAULT NULL,
  `host_response_time` varchar(255) DEFAULT NULL,
  `host_since` datetime(6) DEFAULT NULL,
  `host_years` int DEFAULT NULL,
  `introduction` text,
  `languages` varchar(255) DEFAULT NULL,
  `nickname` varchar(50) DEFAULT NULL,
  `occupation` varchar(100) DEFAULT NULL,
  `birthday` varchar(10) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `id_card_back` varchar(255) DEFAULT NULL,
  `id_card_front` varchar(255) DEFAULT NULL,
  `frequent_guests` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_6dotkott2kjsp8vw4d0m25fb7` (`email`),
  UNIQUE KEY `UK_r43af9ap4edm43mmtq01oddj6` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4904 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `violation_actions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action_type` varchar(255) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `effective_at` datetime(6) DEFAULT NULL,
  `expires_at` datetime(6) DEFAULT NULL,
  `notes` text,
  `reason` varchar(1000) NOT NULL,
  `suspend_days` int DEFAULT NULL,
  `homestay_id` bigint NOT NULL,
  `processor_id` bigint NOT NULL,
  `violation_report_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK8cmvredgicl28pqx36eh9wf65` (`homestay_id`),
  KEY `FKtj87b1le45dandqr42nidk35n` (`processor_id`),
  KEY `FKgmmxbwcnrapaora6ywkebeajr` (`violation_report_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `violation_reports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `details` text,
  `evidence_images` text,
  `process_result` varchar(1000) DEFAULT NULL,
  `processed_at` datetime(6) DEFAULT NULL,
  `reason` varchar(1000) NOT NULL,
  `status` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `violation_type` varchar(255) NOT NULL,
  `homestay_id` bigint NOT NULL,
  `processor_id` bigint DEFAULT NULL,
  `reporter_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK5stg9i97qdxr2m7nhykwafeax` (`homestay_id`),
  KEY `FK984acygdsndp49cnj3lkf5i1n` (`processor_id`),
  KEY `FKljcw7ineko5kdooui3qg1uvlv` (`reporter_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;